version: "3.0"
services: 
  influxdb:
    image: influxdb:latest
    volumes:
      - influxvol:/var/lib/influxdb
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafanavol:/var/lib/grafana
  data_push:
    build: ./data_push
    volumes:
      - ./data_test:/var/lib/data
    network_mode: "host"

volumes:
  influxvol: {}
  grafanavol: {}